[versions]
appcompat = "1.6.1"
gson = "2.10.1"
recyclerview="1.3.2"
material = "1.10.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }


